name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

jobs:
  run:
    name: "Run Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Set up caching for pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: "pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}"
        restore-keys: |
          pip-${{ matrix.python-version }}-

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install and run Ruff for linting
    - name: Lint
      run: |
        pip install ruff
        ruff check . --fix

    # Run the tests
    - name: Run Tests
      run: |
        pip install pytest
        pytest --maxfail=5 --disable-warnings
